<a href="https://colab.research.google.com/github/iamjaykumar/Working_on_numpy/blob/main/numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
print(arr)
print(arr.reshape(6,2))

[[4 9 9 8]
 [4 1 9 9]
 [6 9 7 2]]
[[4 9]
 [9 8]
 [4 1]
 [9 9]
 [6 9]
 [7 2]]


In [4]:
arr.T # .T return the transpose of the array

array([[4, 4, 6],
       [9, 1, 9],
       [9, 9, 7],
       [8, 9, 2]])

In [5]:
arr.flatten() # It will convert into 1D array

array([4, 9, 9, 8, 4, 1, 9, 9, 6, 9, 7, 2])

In [7]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1.ndim)

1


axis = 0 : row, axis = 1 : col

It converts into 2D array across col because axis = 1

In [8]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
arr

array([[4, 9, 9, 8],
       [4, 1, 9, 9],
       [6, 9, 7, 2]])

In [10]:
np.squeeze(arr) #The squeeze() function in NumPy is used to remove axes (dimensions) from an array that have a length of 1

array([[4, 9, 9, 8],
       [4, 1, 9, 9],
       [6, 9, 7, 2]])

In [12]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [13]:
np.squeeze(data) # It converts into single dim array

array([1, 2, 3])

In [14]:
np.repeat(arr1, 3)  # repeating the elememts

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

The np.roll() function takes an array and a shift value as arguments. It rolls the elements of the array along a given axis. In this case, the array being rolled is arr1, which is a one-dimensional array. The shift value is 2. This means that the elements of arr1 will be shifted to the right by 2 positions. The elements that are shifted off the end of the array will reappear at the beginning.

In [15]:
np.roll(arr1, 2) #shift=2

array([4, 5, 1, 2, 3])

This code uses np.diag() on a 1D array (arr1) to create a 2D array with arr1's elements as the main diagonal and zeros elsewhere [1].

In [16]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [18]:
#String Function
arr = np.array(['sudh', 'kumar'])
print(arr)
np.char.upper(arr)
print(np.char.capitalize(arr))
print(np.char.title(arr))

['sudh' 'kumar']
['Sudh' 'Kumar']
['Sudh' 'Kumar']


In [20]:
#Numpy - Mathematical Functions
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))
print(arr1)
print(arr2)

[[3 1 2 5]
 [7 9 8 9]
 [2 1 7 2]]
[[4 5 2 7]
 [1 2 3 6]
 [9 7 8 9]]


In [21]:
print(np.sin(arr1))
print(np.cos(arr1))
print(np.tan(arr1))
print(np.tanh(arr1))
print(np.log(arr1))
print(np.exp(arr1))
print(np.sqrt(arr1))
print(np.power(arr1,2))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.min(arr1))
print(np.max(arr1))


[[ 0.14112001  0.84147098  0.90929743 -0.95892427]
 [ 0.6569866   0.41211849  0.98935825  0.41211849]
 [ 0.90929743  0.84147098  0.6569866   0.90929743]]
[[-0.9899925   0.54030231 -0.41614684  0.28366219]
 [ 0.75390225 -0.91113026 -0.14550003 -0.91113026]
 [-0.41614684  0.54030231  0.75390225 -0.41614684]]
[[-0.14254654  1.55740772 -2.18503986 -3.38051501]
 [ 0.87144798 -0.45231566 -6.79971146 -0.45231566]
 [-2.18503986  1.55740772  0.87144798 -2.18503986]]
[[0.99505475 0.76159416 0.96402758 0.9999092 ]
 [0.99999834 0.99999997 0.99999977 0.99999997]
 [0.96402758 0.76159416 0.99999834 0.96402758]]
[[1.09861229 0.         0.69314718 1.60943791]
 [1.94591015 2.19722458 2.07944154 2.19722458]
 [0.69314718 0.         1.94591015 0.69314718]]
[[2.00855369e+01 2.71828183e+00 7.38905610e+00 1.48413159e+02]
 [1.09663316e+03 8.10308393e+03 2.98095799e+03 8.10308393e+03]
 [7.38905610e+00 2.71828183e+00 1.09663316e+03 7.38905610e+00]]
[[1.73205081 1.         1.41421356 2.23606798]
 [2.64575131 3.  

#Sort , Search & Counting Function

In [22]:
import numpy as np

In [24]:
arr = np.array([1,2,5,7,4,38,2,4,3,545,3234,34,54])
arr

array([   1,    2,    5,    7,    4,   38,    2,    4,    3,  545, 3234,
         34,   54])

In [25]:
np.sort(arr)

array([   1,    2,    2,    3,    4,    4,    5,    7,   34,   38,   54,
        545, 3234])

In [26]:
np.searchsorted(arr, 34)

np.int64(9)

In [28]:
arr1 = np.array([333,4545,324,0,0,0,0,2342])
arr1

array([ 333, 4545,  324,    0,    0,    0,    0, 2342])

In [29]:
np.count_nonzero(arr1)

4

In [30]:
np.where(arr>6) # It will give index

(array([ 3,  5,  9, 10, 11, 12]),)

In [31]:
np.extract(arr>6,arr) # It will give greater than 6 data

array([   7,   38,  545, 3234,   34,   54])

In [32]:
arr.byteswap() # byte swapping

array([   72057594037927936,   144115188075855872,   360287970189639680,
         504403158265495552,   288230376151711744,  2738188573441261568,
         144115188075855872,   288230376151711744,   216172782113783808,
        2378463553205043200, -6770036139844698112,  2449958197289549824,
        3891110078048108544])

In [34]:
a = np.copy(arr) #deep copy: It will not affect the original array
a

array([   1,    2,    5,    7,    4,   38,    2,    4,    3,  545, 3234,
         34,   54])

In [35]:
b = arr.view()  #Shallow copy  : But it will effect original array(Ye kisi dusre location pe copy nahi karta, ye sirf reference add copy karta h)

In [37]:
b[0] = 0
b

array([   0,    2,    5,    7,    4,   38,    2,    4,    3,  545, 3234,
         34,   54])

In [38]:
arr

array([   0,    2,    5,    7,    4,   38,    2,    4,    3,  545, 3234,
         34,   54])

#Numpy- matrix library

In [39]:
import numpy.matlib as nm

In [40]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [41]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [42]:
nm.eye(5) #identity matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy -> Linear Algebra

In [44]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [45]:
print(arr1)
print(arr2)

[[1 1]
 [2 2]]
[[0 1]
 [1 0]]


In [46]:
np.dot(arr1,arr2) # same work as @

array([[1, 1],
       [2, 2]])

In [47]:
arr1@arr2 #it's matrix multiplication

array([[1, 1],
       [2, 2]])