<a href="https://colab.research.google.com/github/iamjaykumar/Working_on_numpy/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy: numerical Python
In Numpy we see about arrays

In [2]:
import numpy as np
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [3]:
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
b = np.matrix(l) #By default matrix is 2d

In [8]:
b

matrix([[1, 2, 3, 4]])

In [9]:
d = np.copy(l)
d

array([1, 2, 3, 4])

In [10]:
l[1] = 400
l

[1, 400, 3, 4]

In [11]:
d # it is the copy created in new location so no changes required

array([1, 2, 3, 4])

The numpy.fromfunction() method is a powerful way to create a NumPy array by defining a function that determines the value of each element based on its coordinates (indices).
In the example provided, np.fromfunction(lambda i,j: i==j,(3,3)):

The function is lambda i,j: i==j. This function takes two arguments, i and j, representing the row and column indices. It returns True if i equals j, and False otherwise.
The shape is (3, 3), indicating a 3x3 array.

In [14]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [15]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [17]:
iterable = (i*i for i in range(5))
np.fromiter(iterable,int)#np.fromiter is a convenient way to create a NumPy array from any object that you can loop over (an iterable), which can be particularly useful when dealing with large datasets or when the data is generated on the fly.

array([ 0,  1,  4,  9, 16])

In [19]:
np.fromstring('234 234',sep=' ')
np.fromstring('234,234',sep=',')

array([234., 234.])

In [21]:
#Numpy data types
l = [2,3,4,5,6]
arr1 = np.array(l)
arr1

array([2, 3, 4, 5, 6])

In [22]:
arr1.ndim # ndim is used to check the number of dimensional array

1

In [24]:
arr2 = np.array([[1,2,3,5,5],[1,3,3,42,4]])
arr2
arr2.ndim # it's  two dimensional

2

In [27]:
print(arr1.size)
print(arr2.size)

5
10


In [28]:
print(arr2.shape)
print(arr1.shape)

(2, 5)
(5,)


In [29]:
list(range(5)) #Range always take integer value

[0, 1, 2, 3, 4]

The np.arange() function is similar to Python's built-in range() function, but it is designed for creating NumPy arrays and can handle floating-point numbers.

In [31]:
np.arange(2.3, 5.3)

array([2.3, 3.3, 4.3])

In [32]:
np.arange(2.3, 5.3, 0.5)

array([2.3, 2.8, 3.3, 3.8, 4.3, 4.8])

In [34]:
list(np.arange(2.3, 5.6, 0.3))  #array to list is also possible

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [35]:
np.linspace(1,5,10) # 1 to 5 it will give 10 values

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [36]:
np.zeros(5) #1D(1 square bracket)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((3,4)) #2D (2 square bracket) 3rows, 4col

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
np.zeros((3,4,2)) #3D (3 square bracket) we have 4 corss 2 and 3 such kind of matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:

np.zeros((3,4,2,3))     #4D  We have 2 cross 3, four such matrixes

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [41]:
arr4 = np.zeros((3,4,2,3))
arr4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [46]:
print(arr4.ndim)
print(np.ones(4))


4
[1. 1. 1. 1.]


In [47]:
# to print Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.logspace(2,5 , 10)     #It will give log value between 2 to 5
                            #And it will give 10 values (between 2 to 5)
                            #By default base value is 10 but we can change

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

playing with random value

In [51]:
np.random.randn(3)
np.random.randn(3,4)

array([[ 1.11548426,  1.41444203, -1.73965657, -0.34369948],
       [ 1.35114394, -0.48805383,  0.82299873,  0.52507112],
       [ 1.47723743, -0.97014184, -2.63834939, -1.54051541]])

In [52]:
arr = np.random.randn(3,4)    #In case of random.randn fun mean is 0 and Standard Dev is 1(Normal Distribution

Integration between pandas and numpy

In [53]:
import pandas as pd

In [54]:
pd.DataFrame(arr)

0         1         2         3
0 -1.520475  0.117338 -1.172156  0.280389
1 -0.470508  0.210570  0.078815  1.051926
2  1.203171 -0.136616 -1.131745 -0.775901

In [56]:
np.random.randint(1,100,(3,4)) # #It will generate random data between 1 to 110 (3 rows and 4 col)

array([[66,  2, 40, 42],
       [87, 38, 49, 58],
       [71, 55, 66, 30]])

In [57]:
np.random.randint(1,100,(300,400))

array([[14, 67, 65, ..., 59, 74, 32],
       [17, 22, 65, ..., 59, 95, 57],
       [14, 63, 54, ..., 99, 17, 10],
       ...,
       [54, 13, 90, ..., 13, 13, 73],
       [97, 95, 14, ..., 81, 19, 40],
       [84, 33, 93, ..., 99, 78, 31]])

In [58]:
pd.DataFrame(np.random.randint(1,100,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     53   74   91    9    2   99   56   19   35   74  ...   26   82   72   
1     47   62   58   27   81   57    7   36    3   77  ...    6   76   42   
2      5   35   41   71   68   60   48   95    8   88  ...   11   34   95   
3     41   70   38   55   12   47   32   71    2   31  ...   79   67   51   
4     54   13   20    5   33   12   46   59   68   86  ...   20   89   27   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   37   87   91   44   80   54   98   10   45   28  ...   44   20   55   
296   83   64   53    8   35   39   80   28   29    5  ...   73   80   35   
297   17   74   36   78   22   73   86   63   80   77  ...   23   54    3   
298   97   72   77   87   30   93   78    3   74   38  ...   92   34   12   
299   81   33   45   31   17   59    4    5   53   50  ...    7   48   18   

     393  394  395  396  397  398  399  
0     45   43   19   31   95    2   16  
1     89   65   47   41   12   98    1  
2     25   13   92   78   20    3   20  
3     79   55   99   68   77   35   90  
4     27   95   12    4   32   63   80  
..   ...  ...  ...  ...  ...  ...  ...  
295   57   47   83   45   69   31   38  
296   40   44   17   12   25   12   50  
297   35   53   27   55   74   37    8  
298   21   20   93   43   41   96   35  
299    2   93   59   59   80   36   64  

[300 rows x 400 columns]

In [59]:
pd.DataFrame(np.random.randint(1,100,(300,400))).to_csv('test.csv') #creating random data and store to csv file

In [61]:
arr = np.random.rand(3,4)
arr

array([[0.36722726, 0.82784099, 0.22609425, 0.50667421],
       [0.14251152, 0.87514567, 0.74428304, 0.18671109],
       [0.76487775, 0.9253063 , 0.44548134, 0.10073228]])

In [62]:
arr.reshape(6,2) # give the own customizable shape

array([[0.36722726, 0.82784099],
       [0.22609425, 0.50667421],
       [0.14251152, 0.87514567],
       [0.74428304, 0.18671109],
       [0.76487775, 0.9253063 ],
       [0.44548134, 0.10073228]])

In [63]:
arr.reshape(6,-437923749237)    #By default it will take 6 cross 2 because there are 12 elements

array([[0.36722726, 0.82784099],
       [0.22609425, 0.50667421],
       [0.14251152, 0.87514567],
       [0.74428304, 0.18671109],
       [0.76487775, 0.9253063 ],
       [0.44548134, 0.10073228]])

In [65]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))
print(arr1)
print(arr2)

[[2 2 1]
 [2 2 2]
 [1 2 1]]
[[2 1 1]
 [1 1 1]
 [1 2 2]]


In [67]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2) # this will not give the matrix multiplication
print(arr1 / arr2)
print(arr1@arr2) #matrix multiplication

[[4 3 2]
 [3 3 3]
 [2 4 3]]
[[ 0  1  0]
 [ 1  1  1]
 [ 0  0 -1]]
[[4 2 1]
 [2 2 2]
 [1 4 2]]
[[1.  2.  1. ]
 [2.  2.  2. ]
 [1.  1.  0.5]]
[[7 6 6]
 [8 8 8]
 [5 5 5]]
